name: Automatisation Météo


on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run-meteo:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Donner les droits d'exécution
        run: chmod +x Extracteur_meteo.sh

      - name: Exécuter le script météo
        run: ./Extracteur_meteo.sh

      - name: Enregistrer les changements sur GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add meteo.txt || true
          git commit -m "Mise à jour automatique météo" || echo "Aucun changement"
          git push
