name: Automatisation Météo

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-meteo:
    runs-on: ubuntu-latest

    permissions:
          contents: write

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3
        with:
          ref: Version-2-script-de-base  
          persist-credentials: true 

      - name: Donner les droits d'exécution
        run: chmod +x Extracteur_meteo.sh

      - name: Exécuter le script météo
        run: ./Extracteur_meteo.sh

      - name: Commit et push des résultats
        run: |
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add .
              git commit -m "Mise à jour automatique météo" || echo "Aucune modification à committer"
              git push
